[package]
name = "wolf_gang"
version = "0.1.0"
authors = ["lyon <lyonbeckers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.7"
legion = "0.2.1"
nalgebra = "0.19.0"
num = "0.2.1"

[lib]
crate-type = ["cdylib"]