[package]
name = "wolf_gang"
version = "0.1.0"
authors = ["lyon <lyonbeckers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.7"
# legion =  { git = "file:/Users/lyon/RustProjects/legion", branch="experimental" } 
legion = { git = "https://github.com/TomGillen/legion.git" }
nalgebra = "0.19.0"
num = "0.2.1"
ron = "0.5.1"
serde = "1.0.104"
approx = "0.3.2"

[lib]
crate-type = ["cdylib"]
